import decodeRanges from '../../decode-ranges.mjs';

export default decodeRanges('gwJwXFFhZJABhvARJjFJjFBhPAiCJh1Jh1Jh1Jh1Jh1Jh1Jh1Jh1Jh1JhfJh1JhFJkVJhFJwdFJglJkrJh_JilJFJkVJiFJFJ4InFJqlJglJjlJn1J1ilJwiFJuCAOAghJg7JiPJkVJlVJh1Jl1JhlJhlJmlJtlJj1JhFJ0y1JhVJiFJ2xzgxwk_JmlJn1JwRVJxKVJ');
