import decodeRanges from '../../decode-ranges.mjs';

export default decodeRanges('wkEQhKBPFMHBBBBhKBgiFDBBBhvIACABhKBgiHBBBBhKBgiFCCAChvHACAChKBgiHACAChKBgiHACAChJCgiRqJJgmDwapCcCcCcCg_QqYFixNhvGhZB4IwZBACh7PhrAiEECChwFjZBjrBAA2QyNhdBPJh1Dh7NhuHg3Ag-DgrJhKHBBBBhKBidNhyNjwNhJDgjNhxJl1Jj1GBAiVHBDhRAhOAmuIADjxGABAAhTFABABmXM');
